### ISSUE TITLE
version of Stanford Parser

### ISSUE THREAD

**Issue by yzhangcs** [hankcs/DeepBiaffineParserMXNet#2]
I convert ptb files to the Stanford Dependency format, using your scripts implemented [here](https://github.com/hankcs/TreebankPreprocessing).
But it seems that the datasets in this repo is a conllu format.
Can you tell me which vesion of Stanford Parser you use to generate the data?
If is version 3.3.0, how can I convert the conllx format to conllu?
Thanks.

**Comment by hankcs** [comment]
3.3.0 is used to convert the treebank to conllx format. See sample data https://github.com/hankcs/DeepBiaffineParserMXNet/blob/master/data/ptb/dev-debug.conllx

**Comment by yzhangcs** [comment]
Thanks
